dist: bionic

language: go

arch:
  - amd64
  - ppc64le
  - arm64
go:
  - 1.15.x
  - 1.16.x
  - tip

jobs:
  allow_failures:
    - go: 'tip'
  include:
    - arch: amd64
      env: GIMME_ARCH=386

script: "make travis"

